#!/bin/bash
set -e

docker build -t canopeneditor -f .devcontainer/Dockerfile .

# Clean output from previous run
rm -f test/OD.*

# Run the container to generate the file
docker run --rm \
  -v "$PWD:/workdir" \
  canopeneditor \
  mono ./CANopenEditor-v4/net481/EDSSharp.exe \
    --infile ./demoDevice.xdd \
    --outfile ./test/OD \
    --type CanOpenNodeV4

# Compare output with expected result for OD.c
if diff -u ./test/OD.c ./test/expected_outputs/OD.c; then
  echo "✅ OD.c OK"
else
  echo "❌ OD.c NOK"
  exit 1
fi

# Compare output with expected result for OD.h
if diff -u \
  <(sed '/^This file was automatically generated by CANopenEditor/d; /^ *Created:/d; /^ *Modified:/d' ./test/expected_outputs/OD.h) \
  <(sed '/^This file was automatically generated by CANopenEditor/d; /^ *Created:/d; /^ *Modified:/d' ./test/OD.h); then
  echo "✅ OD.h OK"
else
  echo "❌ OD.h NOK"
  exit 1
fi